// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bacqaiqfaozzcqhwbpag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhY3FhaXFmYW96emNxaHdicGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MjA2MjksImV4cCI6MjA2NjQ5NjYyOX0.qjhAggDZvhTNPy97xDMsr7xRnxa5LVrq9MlTXX4aj2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);